apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-manager
  namespace: cluster-api-provider-maas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-leader-election-role
  namespace: cluster-api-provider-maas-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - maasclusters
  - maasmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - maasclusters/status
  - maasmachines/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-leader-election-rolebinding
  namespace: cluster-api-provider-maas-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capmaas-leader-election-role
subjects:
- kind: ServiceAccount
  name: capmaas-manager
  namespace: cluster-api-provider-maas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capmaas-manager-role
subjects:
- kind: ServiceAccount
  name: capmaas-manager
  namespace: cluster-api-provider-maas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capmaas-proxy-role
subjects:
- kind: ServiceAccount
  name: capmaas-manager
  namespace: cluster-api-provider-maas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-webhook-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capmaas-manager-role
subjects:
- kind: ServiceAccount
  name: capmaas-manager
  namespace: cluster-api-provider-maas-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-controller-manager-metrics-service
  namespace: cluster-api-provider-maas-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: capmaas-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: capmaas-controller-manager
  name: capmaas-controller-manager
  namespace: cluster-api-provider-maas-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: capmaas-controller-manager
  template:
    metadata:
      labels:
        control-plane: capmaas-controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        env:
        - name: MAAS_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: MAAS_ENDPOINT
              name: capmaas-manager-bootstrap-credentials
        - name: MAAS_API_KEY
          valueFrom:
            secretKeyRef:
              key: MAAS_API_KEY
              name: capmaas-manager-bootstrap-credentials
        image: gcr.io/spectro-images-public/release/cluster-api-provider-maas:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 20Mi
      serviceAccountName: capmaas-manager
      terminationGracePeriodSeconds: 10
