//go:build !ignore_autogenerated_core_v1alpha4
// +build !ignore_autogenerated_core_v1alpha4

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha4

import (
	unsafe "unsafe"

	v1beta1 "github.com/spectrocloud/cluster-api-provider-maas/api/v1beta1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1alpha4 "sigs.k8s.io/cluster-api/api/v1alpha4"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIEndpoint)(nil), (*v1beta1.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_APIEndpoint_To_v1beta1_APIEndpoint(a.(*APIEndpoint), b.(*v1beta1.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.APIEndpoint)(nil), (*APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_APIEndpoint_To_v1alpha4_APIEndpoint(a.(*v1beta1.APIEndpoint), b.(*APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasCluster)(nil), (*v1beta1.MaasCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasCluster_To_v1beta1_MaasCluster(a.(*MaasCluster), b.(*v1beta1.MaasCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasCluster)(nil), (*MaasCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasCluster_To_v1alpha4_MaasCluster(a.(*v1beta1.MaasCluster), b.(*MaasCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasClusterList)(nil), (*v1beta1.MaasClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasClusterList_To_v1beta1_MaasClusterList(a.(*MaasClusterList), b.(*v1beta1.MaasClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasClusterList)(nil), (*MaasClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasClusterList_To_v1alpha4_MaasClusterList(a.(*v1beta1.MaasClusterList), b.(*MaasClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasClusterSpec)(nil), (*v1beta1.MaasClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasClusterSpec_To_v1beta1_MaasClusterSpec(a.(*MaasClusterSpec), b.(*v1beta1.MaasClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasClusterSpec)(nil), (*MaasClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasClusterSpec_To_v1alpha4_MaasClusterSpec(a.(*v1beta1.MaasClusterSpec), b.(*MaasClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasClusterStatus)(nil), (*v1beta1.MaasClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasClusterStatus_To_v1beta1_MaasClusterStatus(a.(*MaasClusterStatus), b.(*v1beta1.MaasClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasClusterStatus)(nil), (*MaasClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasClusterStatus_To_v1alpha4_MaasClusterStatus(a.(*v1beta1.MaasClusterStatus), b.(*MaasClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasMachine)(nil), (*v1beta1.MaasMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasMachine_To_v1beta1_MaasMachine(a.(*MaasMachine), b.(*v1beta1.MaasMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasMachine)(nil), (*MaasMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasMachine_To_v1alpha4_MaasMachine(a.(*v1beta1.MaasMachine), b.(*MaasMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasMachineList)(nil), (*v1beta1.MaasMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasMachineList_To_v1beta1_MaasMachineList(a.(*MaasMachineList), b.(*v1beta1.MaasMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasMachineList)(nil), (*MaasMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasMachineList_To_v1alpha4_MaasMachineList(a.(*v1beta1.MaasMachineList), b.(*MaasMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasMachineSpec)(nil), (*v1beta1.MaasMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasMachineSpec_To_v1beta1_MaasMachineSpec(a.(*MaasMachineSpec), b.(*v1beta1.MaasMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasMachineSpec)(nil), (*MaasMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasMachineSpec_To_v1alpha4_MaasMachineSpec(a.(*v1beta1.MaasMachineSpec), b.(*MaasMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasMachineStatus)(nil), (*v1beta1.MaasMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasMachineStatus_To_v1beta1_MaasMachineStatus(a.(*MaasMachineStatus), b.(*v1beta1.MaasMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasMachineStatus)(nil), (*MaasMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasMachineStatus_To_v1alpha4_MaasMachineStatus(a.(*v1beta1.MaasMachineStatus), b.(*MaasMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasMachineTemplate)(nil), (*v1beta1.MaasMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasMachineTemplate_To_v1beta1_MaasMachineTemplate(a.(*MaasMachineTemplate), b.(*v1beta1.MaasMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasMachineTemplate)(nil), (*MaasMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasMachineTemplate_To_v1alpha4_MaasMachineTemplate(a.(*v1beta1.MaasMachineTemplate), b.(*MaasMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasMachineTemplateList)(nil), (*v1beta1.MaasMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasMachineTemplateList_To_v1beta1_MaasMachineTemplateList(a.(*MaasMachineTemplateList), b.(*v1beta1.MaasMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasMachineTemplateList)(nil), (*MaasMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasMachineTemplateList_To_v1alpha4_MaasMachineTemplateList(a.(*v1beta1.MaasMachineTemplateList), b.(*MaasMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasMachineTemplateResource)(nil), (*v1beta1.MaasMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasMachineTemplateResource_To_v1beta1_MaasMachineTemplateResource(a.(*MaasMachineTemplateResource), b.(*v1beta1.MaasMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasMachineTemplateResource)(nil), (*MaasMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasMachineTemplateResource_To_v1alpha4_MaasMachineTemplateResource(a.(*v1beta1.MaasMachineTemplateResource), b.(*MaasMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MaasMachineTemplateSpec)(nil), (*v1beta1.MaasMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MaasMachineTemplateSpec_To_v1beta1_MaasMachineTemplateSpec(a.(*MaasMachineTemplateSpec), b.(*v1beta1.MaasMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MaasMachineTemplateSpec)(nil), (*MaasMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MaasMachineTemplateSpec_To_v1alpha4_MaasMachineTemplateSpec(a.(*v1beta1.MaasMachineTemplateSpec), b.(*MaasMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Machine)(nil), (*v1beta1.Machine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Machine_To_v1beta1_Machine(a.(*Machine), b.(*v1beta1.Machine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Machine)(nil), (*Machine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Machine_To_v1alpha4_Machine(a.(*v1beta1.Machine), b.(*Machine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Network)(nil), (*v1beta1.Network)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Network_To_v1beta1_Network(a.(*Network), b.(*v1beta1.Network), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Network)(nil), (*Network)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Network_To_v1alpha4_Network(a.(*v1beta1.Network), b.(*Network), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha4_APIEndpoint_To_v1beta1_APIEndpoint(in *APIEndpoint, out *v1beta1.APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	return nil
}

// Convert_v1alpha4_APIEndpoint_To_v1beta1_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha4_APIEndpoint_To_v1beta1_APIEndpoint(in *APIEndpoint, out *v1beta1.APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha4_APIEndpoint_To_v1beta1_APIEndpoint(in, out, s)
}

func autoConvert_v1beta1_APIEndpoint_To_v1alpha4_APIEndpoint(in *v1beta1.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	return nil
}

// Convert_v1beta1_APIEndpoint_To_v1alpha4_APIEndpoint is an autogenerated conversion function.
func Convert_v1beta1_APIEndpoint_To_v1alpha4_APIEndpoint(in *v1beta1.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1beta1_APIEndpoint_To_v1alpha4_APIEndpoint(in, out, s)
}

func autoConvert_v1alpha4_MaasCluster_To_v1beta1_MaasCluster(in *MaasCluster, out *v1beta1.MaasCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_MaasClusterSpec_To_v1beta1_MaasClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_MaasClusterStatus_To_v1beta1_MaasClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MaasCluster_To_v1beta1_MaasCluster is an autogenerated conversion function.
func Convert_v1alpha4_MaasCluster_To_v1beta1_MaasCluster(in *MaasCluster, out *v1beta1.MaasCluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasCluster_To_v1beta1_MaasCluster(in, out, s)
}

func autoConvert_v1beta1_MaasCluster_To_v1alpha4_MaasCluster(in *v1beta1.MaasCluster, out *MaasCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_MaasClusterSpec_To_v1alpha4_MaasClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_MaasClusterStatus_To_v1alpha4_MaasClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_MaasCluster_To_v1alpha4_MaasCluster is an autogenerated conversion function.
func Convert_v1beta1_MaasCluster_To_v1alpha4_MaasCluster(in *v1beta1.MaasCluster, out *MaasCluster, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasCluster_To_v1alpha4_MaasCluster(in, out, s)
}

func autoConvert_v1alpha4_MaasClusterList_To_v1beta1_MaasClusterList(in *MaasClusterList, out *v1beta1.MaasClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.MaasCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_MaasClusterList_To_v1beta1_MaasClusterList is an autogenerated conversion function.
func Convert_v1alpha4_MaasClusterList_To_v1beta1_MaasClusterList(in *MaasClusterList, out *v1beta1.MaasClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasClusterList_To_v1beta1_MaasClusterList(in, out, s)
}

func autoConvert_v1beta1_MaasClusterList_To_v1alpha4_MaasClusterList(in *v1beta1.MaasClusterList, out *MaasClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MaasCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_MaasClusterList_To_v1alpha4_MaasClusterList is an autogenerated conversion function.
func Convert_v1beta1_MaasClusterList_To_v1alpha4_MaasClusterList(in *v1beta1.MaasClusterList, out *MaasClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasClusterList_To_v1alpha4_MaasClusterList(in, out, s)
}

func autoConvert_v1alpha4_MaasClusterSpec_To_v1beta1_MaasClusterSpec(in *MaasClusterSpec, out *v1beta1.MaasClusterSpec, s conversion.Scope) error {
	out.DNSDomain = in.DNSDomain
	if err := Convert_v1alpha4_APIEndpoint_To_v1beta1_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.FailureDomains = *(*[]string)(unsafe.Pointer(&in.FailureDomains))
	return nil
}

// Convert_v1alpha4_MaasClusterSpec_To_v1beta1_MaasClusterSpec is an autogenerated conversion function.
func Convert_v1alpha4_MaasClusterSpec_To_v1beta1_MaasClusterSpec(in *MaasClusterSpec, out *v1beta1.MaasClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasClusterSpec_To_v1beta1_MaasClusterSpec(in, out, s)
}

func autoConvert_v1beta1_MaasClusterSpec_To_v1alpha4_MaasClusterSpec(in *v1beta1.MaasClusterSpec, out *MaasClusterSpec, s conversion.Scope) error {
	out.DNSDomain = in.DNSDomain
	if err := Convert_v1beta1_APIEndpoint_To_v1alpha4_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.FailureDomains = *(*[]string)(unsafe.Pointer(&in.FailureDomains))
	return nil
}

// Convert_v1beta1_MaasClusterSpec_To_v1alpha4_MaasClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_MaasClusterSpec_To_v1alpha4_MaasClusterSpec(in *v1beta1.MaasClusterSpec, out *MaasClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasClusterSpec_To_v1alpha4_MaasClusterSpec(in, out, s)
}

func autoConvert_v1alpha4_MaasClusterStatus_To_v1beta1_MaasClusterStatus(in *MaasClusterStatus, out *v1beta1.MaasClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	if err := Convert_v1alpha4_Network_To_v1beta1_Network(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.FailureDomains = *(*apiv1beta1.FailureDomains)(unsafe.Pointer(&in.FailureDomains))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha4_MaasClusterStatus_To_v1beta1_MaasClusterStatus is an autogenerated conversion function.
func Convert_v1alpha4_MaasClusterStatus_To_v1beta1_MaasClusterStatus(in *MaasClusterStatus, out *v1beta1.MaasClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasClusterStatus_To_v1beta1_MaasClusterStatus(in, out, s)
}

func autoConvert_v1beta1_MaasClusterStatus_To_v1alpha4_MaasClusterStatus(in *v1beta1.MaasClusterStatus, out *MaasClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	if err := Convert_v1beta1_Network_To_v1alpha4_Network(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.FailureDomains = *(*apiv1alpha4.FailureDomains)(unsafe.Pointer(&in.FailureDomains))
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_MaasClusterStatus_To_v1alpha4_MaasClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_MaasClusterStatus_To_v1alpha4_MaasClusterStatus(in *v1beta1.MaasClusterStatus, out *MaasClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasClusterStatus_To_v1alpha4_MaasClusterStatus(in, out, s)
}

func autoConvert_v1alpha4_MaasMachine_To_v1beta1_MaasMachine(in *MaasMachine, out *v1beta1.MaasMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_MaasMachineSpec_To_v1beta1_MaasMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_MaasMachineStatus_To_v1beta1_MaasMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MaasMachine_To_v1beta1_MaasMachine is an autogenerated conversion function.
func Convert_v1alpha4_MaasMachine_To_v1beta1_MaasMachine(in *MaasMachine, out *v1beta1.MaasMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasMachine_To_v1beta1_MaasMachine(in, out, s)
}

func autoConvert_v1beta1_MaasMachine_To_v1alpha4_MaasMachine(in *v1beta1.MaasMachine, out *MaasMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_MaasMachineSpec_To_v1alpha4_MaasMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_MaasMachineStatus_To_v1alpha4_MaasMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_MaasMachine_To_v1alpha4_MaasMachine is an autogenerated conversion function.
func Convert_v1beta1_MaasMachine_To_v1alpha4_MaasMachine(in *v1beta1.MaasMachine, out *MaasMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasMachine_To_v1alpha4_MaasMachine(in, out, s)
}

func autoConvert_v1alpha4_MaasMachineList_To_v1beta1_MaasMachineList(in *MaasMachineList, out *v1beta1.MaasMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.MaasMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_MaasMachineList_To_v1beta1_MaasMachineList is an autogenerated conversion function.
func Convert_v1alpha4_MaasMachineList_To_v1beta1_MaasMachineList(in *MaasMachineList, out *v1beta1.MaasMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasMachineList_To_v1beta1_MaasMachineList(in, out, s)
}

func autoConvert_v1beta1_MaasMachineList_To_v1alpha4_MaasMachineList(in *v1beta1.MaasMachineList, out *MaasMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MaasMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_MaasMachineList_To_v1alpha4_MaasMachineList is an autogenerated conversion function.
func Convert_v1beta1_MaasMachineList_To_v1alpha4_MaasMachineList(in *v1beta1.MaasMachineList, out *MaasMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasMachineList_To_v1alpha4_MaasMachineList(in, out, s)
}

func autoConvert_v1alpha4_MaasMachineSpec_To_v1beta1_MaasMachineSpec(in *MaasMachineSpec, out *v1beta1.MaasMachineSpec, s conversion.Scope) error {
	out.FailureDomain = (*string)(unsafe.Pointer(in.FailureDomain))
	out.SystemID = (*string)(unsafe.Pointer(in.SystemID))
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.ResourcePool = (*string)(unsafe.Pointer(in.ResourcePool))
	out.MinCPU = (*int)(unsafe.Pointer(in.MinCPU))
	out.MinMemoryInMB = (*int)(unsafe.Pointer(in.MinMemoryInMB))
	out.Image = in.Image
	return nil
}

// Convert_v1alpha4_MaasMachineSpec_To_v1beta1_MaasMachineSpec is an autogenerated conversion function.
func Convert_v1alpha4_MaasMachineSpec_To_v1beta1_MaasMachineSpec(in *MaasMachineSpec, out *v1beta1.MaasMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasMachineSpec_To_v1beta1_MaasMachineSpec(in, out, s)
}

func autoConvert_v1beta1_MaasMachineSpec_To_v1alpha4_MaasMachineSpec(in *v1beta1.MaasMachineSpec, out *MaasMachineSpec, s conversion.Scope) error {
	out.FailureDomain = (*string)(unsafe.Pointer(in.FailureDomain))
	out.SystemID = (*string)(unsafe.Pointer(in.SystemID))
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.ResourcePool = (*string)(unsafe.Pointer(in.ResourcePool))
	out.MinCPU = (*int)(unsafe.Pointer(in.MinCPU))
	out.MinMemoryInMB = (*int)(unsafe.Pointer(in.MinMemoryInMB))
	out.Image = in.Image
	return nil
}

// Convert_v1beta1_MaasMachineSpec_To_v1alpha4_MaasMachineSpec is an autogenerated conversion function.
func Convert_v1beta1_MaasMachineSpec_To_v1alpha4_MaasMachineSpec(in *v1beta1.MaasMachineSpec, out *MaasMachineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasMachineSpec_To_v1alpha4_MaasMachineSpec(in, out, s)
}

func autoConvert_v1alpha4_MaasMachineStatus_To_v1beta1_MaasMachineStatus(in *MaasMachineStatus, out *v1beta1.MaasMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.MachineState = (*v1beta1.MachineState)(unsafe.Pointer(in.MachineState))
	out.MachinePowered = in.MachinePowered
	out.Hostname = (*string)(unsafe.Pointer(in.Hostname))
	out.DNSAttached = in.DNSAttached
	out.Addresses = *(*[]apiv1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha4_MaasMachineStatus_To_v1beta1_MaasMachineStatus is an autogenerated conversion function.
func Convert_v1alpha4_MaasMachineStatus_To_v1beta1_MaasMachineStatus(in *MaasMachineStatus, out *v1beta1.MaasMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasMachineStatus_To_v1beta1_MaasMachineStatus(in, out, s)
}

func autoConvert_v1beta1_MaasMachineStatus_To_v1alpha4_MaasMachineStatus(in *v1beta1.MaasMachineStatus, out *MaasMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.MachineState = (*MachineState)(unsafe.Pointer(in.MachineState))
	out.MachinePowered = in.MachinePowered
	out.Hostname = (*string)(unsafe.Pointer(in.Hostname))
	out.DNSAttached = in.DNSAttached
	out.Addresses = *(*[]apiv1alpha4.MachineAddress)(unsafe.Pointer(&in.Addresses))
	out.Conditions = *(*apiv1alpha4.Conditions)(unsafe.Pointer(&in.Conditions))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1beta1_MaasMachineStatus_To_v1alpha4_MaasMachineStatus is an autogenerated conversion function.
func Convert_v1beta1_MaasMachineStatus_To_v1alpha4_MaasMachineStatus(in *v1beta1.MaasMachineStatus, out *MaasMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasMachineStatus_To_v1alpha4_MaasMachineStatus(in, out, s)
}

func autoConvert_v1alpha4_MaasMachineTemplate_To_v1beta1_MaasMachineTemplate(in *MaasMachineTemplate, out *v1beta1.MaasMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_MaasMachineTemplateSpec_To_v1beta1_MaasMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MaasMachineTemplate_To_v1beta1_MaasMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha4_MaasMachineTemplate_To_v1beta1_MaasMachineTemplate(in *MaasMachineTemplate, out *v1beta1.MaasMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasMachineTemplate_To_v1beta1_MaasMachineTemplate(in, out, s)
}

func autoConvert_v1beta1_MaasMachineTemplate_To_v1alpha4_MaasMachineTemplate(in *v1beta1.MaasMachineTemplate, out *MaasMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_MaasMachineTemplateSpec_To_v1alpha4_MaasMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_MaasMachineTemplate_To_v1alpha4_MaasMachineTemplate is an autogenerated conversion function.
func Convert_v1beta1_MaasMachineTemplate_To_v1alpha4_MaasMachineTemplate(in *v1beta1.MaasMachineTemplate, out *MaasMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasMachineTemplate_To_v1alpha4_MaasMachineTemplate(in, out, s)
}

func autoConvert_v1alpha4_MaasMachineTemplateList_To_v1beta1_MaasMachineTemplateList(in *MaasMachineTemplateList, out *v1beta1.MaasMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.MaasMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_MaasMachineTemplateList_To_v1beta1_MaasMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_MaasMachineTemplateList_To_v1beta1_MaasMachineTemplateList(in *MaasMachineTemplateList, out *v1beta1.MaasMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasMachineTemplateList_To_v1beta1_MaasMachineTemplateList(in, out, s)
}

func autoConvert_v1beta1_MaasMachineTemplateList_To_v1alpha4_MaasMachineTemplateList(in *v1beta1.MaasMachineTemplateList, out *MaasMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MaasMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_MaasMachineTemplateList_To_v1alpha4_MaasMachineTemplateList is an autogenerated conversion function.
func Convert_v1beta1_MaasMachineTemplateList_To_v1alpha4_MaasMachineTemplateList(in *v1beta1.MaasMachineTemplateList, out *MaasMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasMachineTemplateList_To_v1alpha4_MaasMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha4_MaasMachineTemplateResource_To_v1beta1_MaasMachineTemplateResource(in *MaasMachineTemplateResource, out *v1beta1.MaasMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_MaasMachineSpec_To_v1beta1_MaasMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MaasMachineTemplateResource_To_v1beta1_MaasMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_MaasMachineTemplateResource_To_v1beta1_MaasMachineTemplateResource(in *MaasMachineTemplateResource, out *v1beta1.MaasMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasMachineTemplateResource_To_v1beta1_MaasMachineTemplateResource(in, out, s)
}

func autoConvert_v1beta1_MaasMachineTemplateResource_To_v1alpha4_MaasMachineTemplateResource(in *v1beta1.MaasMachineTemplateResource, out *MaasMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_MaasMachineSpec_To_v1alpha4_MaasMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_MaasMachineTemplateResource_To_v1alpha4_MaasMachineTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_MaasMachineTemplateResource_To_v1alpha4_MaasMachineTemplateResource(in *v1beta1.MaasMachineTemplateResource, out *MaasMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasMachineTemplateResource_To_v1alpha4_MaasMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_MaasMachineTemplateSpec_To_v1beta1_MaasMachineTemplateSpec(in *MaasMachineTemplateSpec, out *v1beta1.MaasMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_MaasMachineTemplateResource_To_v1beta1_MaasMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MaasMachineTemplateSpec_To_v1beta1_MaasMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_MaasMachineTemplateSpec_To_v1beta1_MaasMachineTemplateSpec(in *MaasMachineTemplateSpec, out *v1beta1.MaasMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_MaasMachineTemplateSpec_To_v1beta1_MaasMachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_MaasMachineTemplateSpec_To_v1alpha4_MaasMachineTemplateSpec(in *v1beta1.MaasMachineTemplateSpec, out *MaasMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_MaasMachineTemplateResource_To_v1alpha4_MaasMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_MaasMachineTemplateSpec_To_v1alpha4_MaasMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_MaasMachineTemplateSpec_To_v1alpha4_MaasMachineTemplateSpec(in *v1beta1.MaasMachineTemplateSpec, out *MaasMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_MaasMachineTemplateSpec_To_v1alpha4_MaasMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_Machine_To_v1beta1_Machine(in *Machine, out *v1beta1.Machine, s conversion.Scope) error {
	out.ID = in.ID
	out.Hostname = in.Hostname
	out.State = v1beta1.MachineState(in.State)
	out.Powered = in.Powered
	out.AvailabilityZone = in.AvailabilityZone
	out.Addresses = *(*[]apiv1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	return nil
}

// Convert_v1alpha4_Machine_To_v1beta1_Machine is an autogenerated conversion function.
func Convert_v1alpha4_Machine_To_v1beta1_Machine(in *Machine, out *v1beta1.Machine, s conversion.Scope) error {
	return autoConvert_v1alpha4_Machine_To_v1beta1_Machine(in, out, s)
}

func autoConvert_v1beta1_Machine_To_v1alpha4_Machine(in *v1beta1.Machine, out *Machine, s conversion.Scope) error {
	out.ID = in.ID
	out.Hostname = in.Hostname
	out.State = MachineState(in.State)
	out.Powered = in.Powered
	out.AvailabilityZone = in.AvailabilityZone
	out.Addresses = *(*[]apiv1alpha4.MachineAddress)(unsafe.Pointer(&in.Addresses))
	return nil
}

// Convert_v1beta1_Machine_To_v1alpha4_Machine is an autogenerated conversion function.
func Convert_v1beta1_Machine_To_v1alpha4_Machine(in *v1beta1.Machine, out *Machine, s conversion.Scope) error {
	return autoConvert_v1beta1_Machine_To_v1alpha4_Machine(in, out, s)
}

func autoConvert_v1alpha4_Network_To_v1beta1_Network(in *Network, out *v1beta1.Network, s conversion.Scope) error {
	out.DNSName = in.DNSName
	return nil
}

// Convert_v1alpha4_Network_To_v1beta1_Network is an autogenerated conversion function.
func Convert_v1alpha4_Network_To_v1beta1_Network(in *Network, out *v1beta1.Network, s conversion.Scope) error {
	return autoConvert_v1alpha4_Network_To_v1beta1_Network(in, out, s)
}

func autoConvert_v1beta1_Network_To_v1alpha4_Network(in *v1beta1.Network, out *Network, s conversion.Scope) error {
	out.DNSName = in.DNSName
	return nil
}

// Convert_v1beta1_Network_To_v1alpha4_Network is an autogenerated conversion function.
func Convert_v1beta1_Network_To_v1alpha4_Network(in *v1beta1.Network, out *Network, s conversion.Scope) error {
	return autoConvert_v1beta1_Network_To_v1alpha4_Network(in, out, s)
}
