# Creates a cluster with one control-plane node
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: MaasCluster
metadata:
  name: t-cluster
  namespace: default
spec:
  dnsDomain: maas.sc
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: t-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: t-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: MaasCluster
    name: t-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: MaasMachineTemplate
metadata:
  name: t-cluster-control-plane
  namespace: default
spec:
  template:
    spec:
      image: u-2004-0-k-1243-0
      minCPU: 4
      minMemory: 8192
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: t-cluster-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          anonymous-auth: "true"
          authorization-mode: RBAC,Node
          default-not-ready-toleration-seconds: "60"
          default-unreachable-toleration-seconds: "60"
          disable-admission-plugins: AlwaysAdmit
          enable-admission-plugins: AlwaysPullImages,NamespaceLifecycle,ServiceAccount,NodeRestriction
        timeoutForControlPlane: 10m0s
      controllerManager:
        extraArgs:
          feature-gates: RotateKubeletServerCertificate=true
          pod-eviction-timeout: 1m0s
          terminated-pod-gc-threshold: "25"
          use-service-account-credentials: "true"
      dns: {}
      etcd: {}
      networking: {}
      scheduler:
        extraArgs: null
    initConfiguration:
      localAPIEndpoint:
        advertiseAddress: ""
        bindPort: 0
      nodeRegistration:
        kubeletExtraArgs:
          event-qps: "0"
          feature-gates: RotateKubeletServerCertificate=true
          read-only-port: "0"
        name: '{{ v1.local_hostname }}'
    joinConfiguration:
      controlPlane:
        localAPIEndpoint:
          advertiseAddress: ""
          bindPort: 0
      discovery: {}
      nodeRegistration:
        kubeletExtraArgs:
          event-qps: "0"
          feature-gates: RotateKubeletServerCertificate=true
          read-only-port: "0"
        name: '{{ v1.local_hostname }}'
    preKubeadmCommands:
    - while [ ! -S /var/run/containerd/containerd.sock ]; do echo 'Waiting for containerd...';
      sleep 1; done
    - sed -ri '/\sswap\s/s/^#?/#/' /etc/fstab
    - swapoff -a
    useExperimentalRetryJoin: true
