//go:build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	"sigs.k8s.io/cluster-api/errors"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIEndpoint) DeepCopyInto(out *APIEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIEndpoint.
func (in *APIEndpoint) DeepCopy() *APIEndpoint {
	if in == nil {
		return nil
	}
	out := new(APIEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUQuotaConfig) DeepCopyInto(out *CPUQuotaConfig) {
	*out = *in
	if in.DefaultLimit != nil {
		in, out := &in.DefaultLimit, &out.DefaultLimit
		*out = new(int32)
		**out = **in
	}
	if in.MaxLimit != nil {
		in, out := &in.MaxLimit, &out.MaxLimit
		*out = new(int32)
		**out = **in
	}
	if in.BurstLimit != nil {
		in, out := &in.BurstLimit, &out.BurstLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUQuotaConfig.
func (in *CPUQuotaConfig) DeepCopy() *CPUQuotaConfig {
	if in == nil {
		return nil
	}
	out := new(CPUQuotaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostOSConfig) DeepCopyInto(out *HostOSConfig) {
	*out = *in
	if in.AutoUpdate != nil {
		in, out := &in.AutoUpdate, &out.AutoUpdate
		*out = new(bool)
		**out = **in
	}
	if in.MaintenanceWindow != nil {
		in, out := &in.MaintenanceWindow, &out.MaintenanceWindow
		*out = new(MaintenanceWindow)
		(*in).DeepCopyInto(*out)
	}
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdateConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostOSConfig.
func (in *HostOSConfig) DeepCopy() *HostOSConfig {
	if in == nil {
		return nil
	}
	out := new(HostOSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRepositoryCertificates) DeepCopyInto(out *ImageRepositoryCertificates) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRepositoryCertificates.
func (in *ImageRepositoryCertificates) DeepCopy() *ImageRepositoryCertificates {
	if in == nil {
		return nil
	}
	out := new(ImageRepositoryCertificates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRepositoryConfig) DeepCopyInto(out *ImageRepositoryConfig) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(ImageRepositoryCredentials)
		**out = **in
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = new(ImageRepositoryCertificates)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRepositoryConfig.
func (in *ImageRepositoryConfig) DeepCopy() *ImageRepositoryConfig {
	if in == nil {
		return nil
	}
	out := new(ImageRepositoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRepositoryCredentials) DeepCopyInto(out *ImageRepositoryCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRepositoryCredentials.
func (in *ImageRepositoryCredentials) DeepCopy() *ImageRepositoryCredentials {
	if in == nil {
		return nil
	}
	out := new(ImageRepositoryCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureClusterRef) DeepCopyInto(out *InfrastructureClusterRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureClusterRef.
func (in *InfrastructureClusterRef) DeepCopy() *InfrastructureClusterRef {
	if in == nil {
		return nil
	}
	out := new(InfrastructureClusterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LXDConfig) DeepCopyInto(out *LXDConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ImageRepository != nil {
		in, out := &in.ImageRepository, &out.ImageRepository
		*out = new(ImageRepositoryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HostOS != nil {
		in, out := &in.HostOS, &out.HostOS
		*out = new(HostOSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityConfig != nil {
		in, out := &in.SecurityConfig, &out.SecurityConfig
		*out = new(SecurityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SkipNetworkUpdate != nil {
		in, out := &in.SkipNetworkUpdate, &out.SkipNetworkUpdate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LXDConfig.
func (in *LXDConfig) DeepCopy() *LXDConfig {
	if in == nil {
		return nil
	}
	out := new(LXDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasCluster) DeepCopyInto(out *MaasCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasCluster.
func (in *MaasCluster) DeepCopy() *MaasCluster {
	if in == nil {
		return nil
	}
	out := new(MaasCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaasCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasClusterList) DeepCopyInto(out *MaasClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaasCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasClusterList.
func (in *MaasClusterList) DeepCopy() *MaasClusterList {
	if in == nil {
		return nil
	}
	out := new(MaasClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaasClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasClusterSpec) DeepCopyInto(out *MaasClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LXDConfig != nil {
		in, out := &in.LXDConfig, &out.LXDConfig
		*out = new(LXDConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasClusterSpec.
func (in *MaasClusterSpec) DeepCopy() *MaasClusterSpec {
	if in == nil {
		return nil
	}
	out := new(MaasClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasClusterStatus) DeepCopyInto(out *MaasClusterStatus) {
	*out = *in
	out.Network = in.Network
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(apiv1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasClusterStatus.
func (in *MaasClusterStatus) DeepCopy() *MaasClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MaasClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasMachine) DeepCopyInto(out *MaasMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasMachine.
func (in *MaasMachine) DeepCopy() *MaasMachine {
	if in == nil {
		return nil
	}
	out := new(MaasMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaasMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasMachineList) DeepCopyInto(out *MaasMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaasMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasMachineList.
func (in *MaasMachineList) DeepCopy() *MaasMachineList {
	if in == nil {
		return nil
	}
	out := new(MaasMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaasMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasMachineSpec) DeepCopyInto(out *MaasMachineSpec) {
	*out = *in
	if in.FailureDomain != nil {
		in, out := &in.FailureDomain, &out.FailureDomain
		*out = new(string)
		**out = **in
	}
	if in.SystemID != nil {
		in, out := &in.SystemID, &out.SystemID
		*out = new(string)
		**out = **in
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.ResourcePool != nil {
		in, out := &in.ResourcePool, &out.ResourcePool
		*out = new(string)
		**out = **in
	}
	if in.MinCPU != nil {
		in, out := &in.MinCPU, &out.MinCPU
		*out = new(int)
		**out = **in
	}
	if in.MinMemoryInMB != nil {
		in, out := &in.MinMemoryInMB, &out.MinMemoryInMB
		*out = new(int)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LXD != nil {
		in, out := &in.LXD, &out.LXD
		*out = new(MachineLXDConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.StaticIP != nil {
		in, out := &in.StaticIP, &out.StaticIP
		*out = new(StaticIPConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasMachineSpec.
func (in *MaasMachineSpec) DeepCopy() *MaasMachineSpec {
	if in == nil {
		return nil
	}
	out := new(MaasMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasMachineStatus) DeepCopyInto(out *MaasMachineStatus) {
	*out = *in
	if in.MachineState != nil {
		in, out := &in.MachineState, &out.MachineState
		*out = new(MachineState)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]apiv1beta1.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(errors.MachineStatusError)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasMachineStatus.
func (in *MaasMachineStatus) DeepCopy() *MaasMachineStatus {
	if in == nil {
		return nil
	}
	out := new(MaasMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasMachineTemplate) DeepCopyInto(out *MaasMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasMachineTemplate.
func (in *MaasMachineTemplate) DeepCopy() *MaasMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(MaasMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaasMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasMachineTemplateList) DeepCopyInto(out *MaasMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaasMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasMachineTemplateList.
func (in *MaasMachineTemplateList) DeepCopy() *MaasMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(MaasMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaasMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasMachineTemplateResource) DeepCopyInto(out *MaasMachineTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasMachineTemplateResource.
func (in *MaasMachineTemplateResource) DeepCopy() *MaasMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(MaasMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaasMachineTemplateSpec) DeepCopyInto(out *MaasMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaasMachineTemplateSpec.
func (in *MaasMachineTemplateSpec) DeepCopy() *MaasMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(MaasMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Machine) DeepCopyInto(out *Machine) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]apiv1beta1.MachineAddress, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Machine.
func (in *Machine) DeepCopy() *Machine {
	if in == nil {
		return nil
	}
	out := new(Machine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineLXDConfig) DeepCopyInto(out *MachineLXDConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.VMConfig != nil {
		in, out := &in.VMConfig, &out.VMConfig
		*out = new(VMConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineLXDConfig.
func (in *MachineLXDConfig) DeepCopy() *MachineLXDConfig {
	if in == nil {
		return nil
	}
	out := new(MachineLXDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryQuotaConfig) DeepCopyInto(out *MemoryQuotaConfig) {
	*out = *in
	if in.DefaultLimit != nil {
		in, out := &in.DefaultLimit, &out.DefaultLimit
		*out = new(int32)
		**out = **in
	}
	if in.MaxLimit != nil {
		in, out := &in.MaxLimit, &out.MaxLimit
		*out = new(int32)
		**out = **in
	}
	if in.SwapLimit != nil {
		in, out := &in.SwapLimit, &out.SwapLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryQuotaConfig.
func (in *MemoryQuotaConfig) DeepCopy() *MemoryQuotaConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryQuotaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiTenancyConfig) DeepCopyInto(out *MultiTenancyConfig) {
	*out = *in
	if in.EnableIsolation != nil {
		in, out := &in.EnableIsolation, &out.EnableIsolation
		*out = new(bool)
		**out = **in
	}
	if in.TenantLabels != nil {
		in, out := &in.TenantLabels, &out.TenantLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceSharing != nil {
		in, out := &in.ResourceSharing, &out.ResourceSharing
		*out = new(ResourceSharingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiTenancyConfig.
func (in *MultiTenancyConfig) DeepCopy() *MultiTenancyConfig {
	if in == nil {
		return nil
	}
	out := new(MultiTenancyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Network) DeepCopyInto(out *Network) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Network.
func (in *Network) DeepCopy() *Network {
	if in == nil {
		return nil
	}
	out := new(Network)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkIsolationConfig) DeepCopyInto(out *NetworkIsolationConfig) {
	*out = *in
	if in.EnableVLAN != nil {
		in, out := &in.EnableVLAN, &out.EnableVLAN
		*out = new(bool)
		**out = **in
	}
	if in.DefaultVLAN != nil {
		in, out := &in.DefaultVLAN, &out.DefaultVLAN
		*out = new(int32)
		**out = **in
	}
	if in.NetworkPolicies != nil {
		in, out := &in.NetworkPolicies, &out.NetworkPolicies
		*out = make([]NetworkPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkIsolationConfig.
func (in *NetworkIsolationConfig) DeepCopy() *NetworkIsolationConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkIsolationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicy) DeepCopyInto(out *NetworkPolicy) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]NetworkRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy.
func (in *NetworkPolicy) DeepCopy() *NetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRule) DeepCopyInto(out *NetworkRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRule.
func (in *NetworkRule) DeepCopy() *NetworkRule {
	if in == nil {
		return nil
	}
	out := new(NetworkRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceIsolationConfig) DeepCopyInto(out *ResourceIsolationConfig) {
	*out = *in
	if in.CPUQuota != nil {
		in, out := &in.CPUQuota, &out.CPUQuota
		*out = new(CPUQuotaConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryQuota != nil {
		in, out := &in.MemoryQuota, &out.MemoryQuota
		*out = new(MemoryQuotaConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageQuota != nil {
		in, out := &in.StorageQuota, &out.StorageQuota
		*out = new(StorageQuotaConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceIsolationConfig.
func (in *ResourceIsolationConfig) DeepCopy() *ResourceIsolationConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceIsolationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSharingConfig) DeepCopyInto(out *ResourceSharingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSharingConfig.
func (in *ResourceSharingConfig) DeepCopy() *ResourceSharingConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceSharingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateConfig) DeepCopyInto(out *RollingUpdateConfig) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int32)
		**out = **in
	}
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(int32)
		**out = **in
	}
	if in.MinReadySeconds != nil {
		in, out := &in.MinReadySeconds, &out.MinReadySeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateConfig.
func (in *RollingUpdateConfig) DeepCopy() *RollingUpdateConfig {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	if in.NetworkIsolation != nil {
		in, out := &in.NetworkIsolation, &out.NetworkIsolation
		*out = new(NetworkIsolationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceIsolation != nil {
		in, out := &in.ResourceIsolation, &out.ResourceIsolation
		*out = new(ResourceIsolationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiTenancy != nil {
		in, out := &in.MultiTenancy, &out.MultiTenancy
		*out = new(MultiTenancyConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticIPConfig) DeepCopyInto(out *StaticIPConfig) {
	*out = *in
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticIPConfig.
func (in *StaticIPConfig) DeepCopy() *StaticIPConfig {
	if in == nil {
		return nil
	}
	out := new(StaticIPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageQuotaConfig) DeepCopyInto(out *StorageQuotaConfig) {
	*out = *in
	if in.DefaultLimit != nil {
		in, out := &in.DefaultLimit, &out.DefaultLimit
		*out = new(int32)
		**out = **in
	}
	if in.MaxLimit != nil {
		in, out := &in.MaxLimit, &out.MaxLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageQuotaConfig.
func (in *StorageQuotaConfig) DeepCopy() *StorageQuotaConfig {
	if in == nil {
		return nil
	}
	out := new(StorageQuotaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMConfig) DeepCopyInto(out *VMConfig) {
	*out = *in
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(int)
		**out = **in
	}
	if in.AutoStart != nil {
		in, out := &in.AutoStart, &out.AutoStart
		*out = new(bool)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(VMResourceLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMConfig.
func (in *VMConfig) DeepCopy() *VMConfig {
	if in == nil {
		return nil
	}
	out := new(VMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMResourceLimits) DeepCopyInto(out *VMResourceLimits) {
	*out = *in
	if in.CPULimit != nil {
		in, out := &in.CPULimit, &out.CPULimit
		*out = new(string)
		**out = **in
	}
	if in.MemoryLimit != nil {
		in, out := &in.MemoryLimit, &out.MemoryLimit
		*out = new(string)
		**out = **in
	}
	if in.DiskIOPS != nil {
		in, out := &in.DiskIOPS, &out.DiskIOPS
		*out = new(int)
		**out = **in
	}
	if in.NetworkBandwidth != nil {
		in, out := &in.NetworkBandwidth, &out.NetworkBandwidth
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMResourceLimits.
func (in *VMResourceLimits) DeepCopy() *VMResourceLimits {
	if in == nil {
		return nil
	}
	out := new(VMResourceLimits)
	in.DeepCopyInto(out)
	return out
}
