apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntupod
  name: maaspod
spec:
  containers:
  - image: "BUILDER_IMG"
    imagePullPolicy: Always
    name: ubuntupod
    command:
    - /image-builder/images/capi/buildmaasimage.sh
    - "1.19.10"
# we can provide multiple versions 
#    - "1.19.12"
#    - "1.20.6"
#    - "1.20.7"
#    - "1.20.8"
#    - "1.21.0"
#    - "1.21.1"
#    - "1.21.2"
    resources: {}
    securityContext:
      privileged: true
    envFrom:
    - secretRef:
        name: aws-credentials
    volumeMounts:
    - mountPath: /dev
      name: devices
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - name: outputdir
      mountPath: /root/image-builder/images/capi/output
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: kvm-path
    hostPath:
      path: /dev/kvm
      type: CharDevice
  - name: devices
    hostPath:
      path: /dev
  - name: modules
    hostPath:
      path: /lib/modules
  - name: outputdir
    hostPath:
      path: /tmp/mypath
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
status: {}
