---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lxd-initializer
  labels:
    app: lxd-initializer
    cluster.x-k8s.io/provider: infrastructure-maas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lxd-initializer
  labels:
    app: lxd-initializer
    cluster.x-k8s.io/provider: infrastructure-maas
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lxd-initializer
  labels:
    app: lxd-initializer
    cluster.x-k8s.io/provider: infrastructure-maas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lxd-initializer
subjects:
- kind: ServiceAccount
  name: lxd-initializer
  namespace: default